eteran/edb-debugger

README.md
Based on our last discussion about the issue #139 `Build fails under Fedora 21 using Qt4` and your [last commit](https://github.com/eteran/edb-debugger/commit/d789bea6f2c246dc250e208cf89b0329f6e87b55) I propose you to add a section `Cloning` to the README.md file.
With respect,
~ Cristian "Dr.Optix" Dinu
=> Update README.md to add info section about cloning

plugins/DebuggerCore/unix/linux/PlatformState.cpp
On x86 systems the original code made false assumptions about sizeof(long double) and layout of `fpregs_.st_space`. As a result, MMX registers showed garbage, and FPU ones were always zero. The first two commits fix this and thus allow to see nonzero (and correct) FPU registers as well as correct MMX registers.
Also, on both x86 and x86-64, `PlatformState::mmx_register()` assumed that `mm0-mm7` map to `st(0)-st(7)`, while in reality they map to `R0-R7`, which aren't organized as stack. The third commit fixes this mistake, thus showing correct results for instructions like `movd mm5,eax` independently of the value of `TOP` bits in FPU status word.
=> Fix for FPU and MMX register presentation

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h
Following GDB, this commit makes use of `PTRACE_GETFPXREGS` instead of `PTRACE_GETFPREGS` on x86 targets. This way we get 1) support for reading SSE registers and 2) common format of `st_space` between x86 and x86-64.
Although in GDB there's also some code to check whether `PTRACE_GETFPXREGS` is supported, that code dates back to 1999 and is likely to be not needed these days. I've checked on Ubuntu 12.04, and `PTRACE_GETFPXREGS` works there too. So I assume any modern system with necessary version of Qt does also support `PTRACE_GETFPXREGS`.
=> Add support for reading SSE registers on x86 systems

src/arch/x86/ArchProcessor.cpp, src/arch/x86_64/ArchProcessor.cpp
This set of patches makes analysis view of instructions like `fld tbyte ptr [...]` and `movaps xmm0,xmmword ptr [...]` (and on x86 also `movq mm0, qword ptr [...]`) show correct values referred by the instructions.
I'm not sure though whether it's a good idea to use `uint32_t` for target on x86 and `uint64_t` on x86_64 — maybe use `uint64_t` on both, then the code would be identical (up to ordering of `switch` cases). But at least, the current way does work, so it's the matter of future changes.
=> Properly show memory expressions of sizes larger than ptrdiff_t

include/Util.h, src/arch/x86/ArchProcessor.cpp, src/arch/x86_64/ArchProcessor.cpp
This fixes bug #159.
Please check that this builds on x86, I don't have access to such a system currently.
=> Fix precision and range loss when printing long double

include/Register.h, include/Types.h, include/arch/x86/ArchTypes.h, include/arch/x86_64/ArchTypes.h, plugins/Analyzer/Analyzer.cpp, plugins/Analyzer/AnalyzerWidget.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/PlatformEvent.cpp, plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, src/Debugger.cpp, src/DialogInputValue.cpp, src/RegionBuffer.h, src/arch/x86/ArchProcessor.cpp, src/arch/x86_64/ArchProcessor.cpp, src/edb.cpp
This set of patches allows to use generic functions like `toHexString()` or `signedFromString()` instead of hand-coding width, filling char etc. in much more places. Also it prepares the `valueXX` types to usage in a future X86 platform state, where it'll be useful to e.g. load value of XMM register from storage space of ZMM registers etc.
Also there are some minor cleanups like removing unnecessary conditional compilation, removing uses of deprecated `QString::sprintf()` functions, and a bit more.
=> Add some functionality to `valueXX` types, use them in more places, including `reg_t` and `address_t`

src/arch/x86/ArchProcessor.cpp, src/arch/x86_64/ArchProcessor.cpp
These two commits allow to print GPRs in the view under disassembly correctly with respect to operand size. This partially solves #156, but still shows garbage (as before) for FPU, MMX and SSE registers.
=> Print correctly-sized values for operands of sizes up to sizeof(reg_t)

src/Debugger.cpp, src/Debugger.h, src/Debugger.ui
This two patches the lack of Toggle Breakpoint and Run To This Line actions and shortcuts for them. I've removed the "Add Breakpoint" action and replaced it with Toggle Breakpoint as a more general one and making more sense since it'd be strange to add multiple breakpoints at the same place (unless they are conditional, but for that there's a separate menu item).
=> Add keyboard shortcuts for Toggle Breakpoint and Run To This Line actions

include/Register.h, include/Util.h, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/Register.cpp, src/arch/x86/ArchProcessor.cpp, src/arch/x86_64/ArchProcessor.cpp
This set of patches fixes both #156 and #161 (until the disassembler supports AVX and other ISA extensions which introduce new/expand old registers).
In any case, even when the new extensions are supported, we'll no longer see wrong zeros or incorrectly-sized values in analysis view. Instead we'll get `(Error: error description)` in place of the value, which is much more useful than wrong value.
=> Do show ST(i), MMi and XMMi registers in analysis view

src/arch/x86_64/ArchProcessor.cpp
I forgot to do this for x86_64 ArchProcessor in the previous pull request.
=> Fix hex number presentation in x86_64 FPU view too

src/arch/x86/ArchProcessor.cpp, src/arch/x86_64/ArchProcessor.cpp
This improves FPU register view, so that the user can easily see not only masked exceptions, but also flags of exceptions occured and more visible unmasked exceptions. Also tells what type of stack fault occured: overflow or underflow.
=> Show which FPU exceptions have or would have happened in register view

README.md, common.pri, debugger.pro, plugins/plugins-x86.pri, plugins/plugins-x86_64.pri, src/Configuration.cpp, src/src.pro
These patches make it possible to specify installation prefix on `qmake` stage, rather than having to set `INSTALL_ROOT` every time you install EDB. Also the default plugin path is now set to `../lib{,64}/edb/` relative to `edb` binary location dir; `lib` vs `lib64` is chosen depending on current arch.
Thus, now it works out of the box when the user does `qmake; make; make install`, installing to `/usr/local/`, as is traditional for GNU packages, and allows to easily do thing similar to autotools' `--prefix=/usr/` option, namely `qmake PREFIX=/usr/` or similar.
=> Improve defaults for installation directory

src/Debugger.cpp, src/Debugger.h
This patch adds a symmetric option to "Run To This Line" functionality, similar to already present `Shift+F7/F8/F9`. Now on `Shift+F4` a Run To This Line command is executed, passing signal to application. Otherwise one would have to do something like `F4, Enter, Shift+F9` to run to current line from exception trap.
=> Add an action and a shortcut to Run To This Line, passing signal to application

src/Debugger.cpp
This commit fixes a crash when e.g. you start a program and press `F4`, which gives you an error message and fails to create the breakpoint. The crash occured due to trying to set one-time mode of the breakpoint, not having checked validity of the pointer.
=> Don't dereference NULL pointer on failure to create a breakpoint

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/arch/x86-generic/ArchProcessor.cpp, src/edb.cpp
This set of commits stops showing zeros in place of unknown segment bases for FS and GS registers, prevents using the wrong values in analysis and fixes my stupid bug of trying to use segment bases before they've been obtained.
=> Fix some issues with FS & GS segment bases

plugins/Assembler/DialogAssembler.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/PlatformEvent.cpp, src/Debugger.cpp, src/arch/x86-generic/ArchProcessor.cpp
This set of patches makes some improvements to presentation of segment registers and FPU control and status words, namely highlights their changes. Also empty FPU registers are now shaded. Also, segment registers are now presented in architectural order, as already were the GPRs.
Other changes are not as vsible to the user, but they somewhat simplify my future changes to support non-native bitness of debuggee.
=> Improve registers presentation

plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/arch/x86-generic/ArchProcessor.cpp, src/capstone-edb/Instruction.cpp
These commits add some more checking of validity of data before returning them as valid `Register`.
Also one of them fixes my error in `Instruction::operator=`, which led Analyzer to crash after doing analysis and then scrolling up disassembly view.
=> Check that SIMD registers have been filled before returning values

src/Debugger.cpp, src/Debugger.ui
This set of commits adds several keyboard shortcuts to already existing functionality. The shortcuts are identical to those used in OllyDbg.
Also one of the commits deduplicates definitions of the shortcuts, which were previously present in at least two places: one at the `connect` call, the other on menu creation.
=> Keyboard shortcuts pack

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h
These commits remove repeating code to get & set debug registers. Also they remove special-casing `DR4` and `DR5`. Although these registers are reserved/aliased to `DR6`&`DR7`, it's the responsibility of the kernel to avoid reading & writing them. EDB just peeks & pokes the `user` struct, so no need to worry.
=> Deduplicate get/set debug register

src/arch/x86-generic/ArchProcessor.cpp
This fixes GPR editing after my recent commits where I made registers names more generic, breaking this functionality.
=> Fix register editing after making QTreeWidgetItems for GPRs generically-named

include/IDebugger.h, include/arch/x86-generic/ArchTypes.h, include/edb.h, plugins/Assembler/DialogAssembler.cpp, plugins/DebuggerCore/unix/DebuggerCoreUNIX.cpp, plugins/DebuggerCore/unix/DebuggerCoreUNIX.h, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, plugins/DebuggerCore/unix/linux/PlatformState.h, plugins/DumpState/DumpState.cpp, src/Configuration.cpp, src/Debugger.cpp, src/arch/x86-generic/ArchProcessor.cpp, src/edb.cpp, src/widgets/QDisassemblyView.cpp
This is most likely the last set of conservative changes regarding support for foreign bitness. I expect that the next set will switch `address_t` and `reg_t` to unconditional 64 bit types, thus changing behavior in many places. After that the only thing remaining would be bug fixes.
=> Gradual preparation for dynamic bitness, part three

include/IProcess.h, include/Register.h, include/Types.h, include/arch/x86-generic/ArchTypes.h, include/edb.h, plugins/Analyzer/AnalyzerWidget.cpp, plugins/BinaryInfo/ELF32.cpp, plugins/BinarySearcher/DialogASCIIString.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, plugins/DebuggerCore/unix/linux/PlatformEvent.cpp, plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, plugins/DebuggerCore/unix/linux/PlatformProcess.h, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, plugins/HeapAnalyzer/DialogHeap.cpp, plugins/HeapAnalyzer/DialogHeap.h, plugins/References/DialogReferences.cpp, src/CallStack.cpp, src/CommentServer.cpp, src/Configuration.cpp, src/Debugger.cpp, src/Debugger.h, src/DialogInputValue.cpp, src/DialogInputValue.h, src/QLongValidator.h, src/QULongValidator.h, src/arch/x86-generic/ArchProcessor.cpp, src/edb.cpp
This set of commits switches `address_t` and `reg_t` to unconditional 64 bit types along with many implied changes. Now non-native bitness can be called supported (although the non-native warning dialog hasn't been changed/removed yet).
This of course needs much testing, as it appears to be quite a significant change, and I alone can't test it well enough.
Now that this has touched so many parts of code, upstream changes have also begun to conflict with it, so it seems it's better to merge it and do any further fixes in new pull requests.
=> Switch address_t and reg_t to unconditional 64 bit

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, src/Debugger.cpp
These fix a few problems with presenting registers due to 64-bit `reg_t` on 32-bit OS/debuggee.
=> A few fixes

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/Debugger.cpp, src/arch/x86-generic/ArchProcessor.cpp
This set of commits enables showing bases for all segment registers, for which it makes sense. Now the kernel isn't trusted about bases of FS&GS for 32-bit process since it's always given as zero.
Also, non-native binary message is only showed on 32-bit EDB, with correspondinly changed text. We consider 32-bit debuggee@64-bit EDB supported now, while 64-bit debuggee on 32-bit EDB is not completely supported yet (due to the limitations of 32-bit syscalls).
=> Show bases of all relevant segment registers

src/arch/x86-generic/ArchProcessor.cpp, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h
This set of commits switches the logic from using segment override prefixes to determining the segment to get base of to direct queries of segment from operand.
=> Address calculation

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/arch/x86-generic/ArchProcessor.cpp
This implements some functions to edit MMx registers using current dialog.
SSE/AVX registers are still not editable, nor are there any usable ways to set them via `DebuggerCore::set_state()`.
=> Make it possible to actually edit MMx registers

include/ArchProcessor.h, src/Debugger.cpp, src/arch/x86-generic/ArchProcessor.cpp
This is a first step to make it possible to have arch-specific register edit dialogs. Currently this doesn't do much, just moves a piece of code to ArchProcessor. Also a commit here prevents crash when clicking OK in unsupported register edit dialog.
Requesting merge just to make sure users don't get annoyed when cloning master and getting crashes :)
=> Move register editing logic to ArchProcessor and prevent crash

include/Util.h, src/QLongValidator.cpp, src/QULongValidator.cpp, src/arch/x86-generic/ArchProcessor.cpp, src/arch/x86-generic/DialogEditGPR.cpp, src/arch/x86-generic/DialogEditGPR.h, src/arch/x86-generic/GPREdit.cpp, src/arch/x86-generic/GPREdit.h, src/src.pro
This set of commits implements a dialog to edit registers, mainly GPRs and segment registers, which basically clones the functionality of OllyDbg's counterpart.
Editing SIMD registers is currently unsupported (including MMX), as isn't editing of FPU registers.
=> New dialog to edit GPRs

include/ArchProcessor.h, include/Util.h, src/Debugger.cpp, src/arch/x86-generic/ArchProcessor.cpp, src/arch/x86-generic/DialogEditSIMDRegister.cpp, src/arch/x86-generic/DialogEditSIMDRegister.h
This set of commits makes it possible to choose format of SIMD registers, i.e. integers of particular sizes or floats/doubles. User chooses the format using a context menu similar to that of OllyDbg.
=> SIMD registers configurable presentation in different formats

plugins/BinaryInfo/BinaryInfo.cpp, plugins/BinaryInfo/BinaryInfo.h, plugins/BinaryInfo/BinaryInfo.pro, plugins/BinaryInfo/OptionsPage.cpp, plugins/BinaryInfo/OptionsPage.h, plugins/BinaryInfo/OptionsPage.ui, plugins/BinaryInfo/demangle.h, plugins/BinaryInfo/symbols.cpp, src/SymbolManager.cpp
This set of commits adds an option to demangle all auto-generated symbols and performs demangling if it's enabled.
Also, now separator between module and symbol names is changed to `!` to avoid confusion with C++ scope resolution operator. (Note that I've seen usage of `!` in a bunch of Windows apps, e.g. IDA and Borland Turbo Debugger AFAIR.)
=> Add support for C++ symbol demangling

plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/arch/x86-generic/ArchProcessor.cpp
This enables EDB to analyze interrupted system calls. An unexpected side effect of this is that newly launched process appears to have interrupted `execve` call, with all arguments `NULL`. Although it's correct, I'm not sure it's worth showing. But for now I think it should be OK.
=> Interrupted syscall analysis

src/Debugger.cpp
This takes into account the change from `::` to `!`.
=> Look for correctly prefixed main

src/arch/x86-generic/ArchProcessor.cpp
This fixes analysis view of operands like `ymmword ptr [ebp+0x318]`.
(Something seems to have gone wrong with #291, this is a retry.)
=> Fix for operands of TYPE_EXPRESSION256

src/FloatX.cpp, src/arch/x86-generic/ArchProcessor.cpp, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h
This makes analysis view more useful when tracing FPU computations.
Also some minor changes have been done to the way unsupported values and infinities are showed.
=> Show FPU operands according to their type in analysis view

include/ArchProcessor.h, plugins/DebuggerCore/unix/linux/PlatformState.cpp, plugins/DebuggerCore/unix/linux/PlatformState.h, src/arch/x86-generic/ArchProcessor.cpp
This allows the user to choose to view FPU as hex/float and as `ST(i)`/`Ri`.
=> FPU display modes

src/arch/x86-generic/ArchProcessor.cpp
The first commit fixes a mistake I had already warned against in my own comment to #208 %)
The second one adds additional clue as to what happens if you press F7/F8/F9.
=> Fix detection of interrupted syscall

plugins/Assembler/DialogAssembler.cpp
This fixes the necessity for the user to press Ctrl+A after pressing Enter to be able to just continue entering the assembly code. Now when the Assemble dialog is shown, it focuses the assembly field, and when Enter is pressed, regardless of the result (success or failure), the entry is focused and its text is selected, since it's the most likely thing the user would expect (enter next instruction or fix erroneous one).
=> Improve user experience with Assemble dialog

plugins/Assembler/DialogAssembler.cpp, plugins/Assembler/DialogAssembler.ui
This makes it possible to toggle checkboxes in Assemble dialog, but not lose focus from the instruction entry. The checkboxes can still be focused by `Tab`, but now it's also possible to just use their shortcuts.
=> Some minor Assembly dialog improvements

plugins/DebuggerCore/unix/linux/PlatformProcess.cpp
This code has been a mystery for me until I sat down and tried to understand what it does. I've now reworked it a bit to simplify logic, so now it doesn't do unnecessary endianness checks and is quite straightforward to read.
Also, with an additional commit, the memory writers, which use `/proc/pid/mem`, now open memory in unbuffered mode, since it appears that even if an error will occur when writing, `QFile` won't notice until the file is closed, and will happily report that all bytes have been written.
=> Simplify reading and writing of single bytes

.travis.yml
This removes warnings for Qt4 headers and those about ["missing" braces](http://stackoverflow.com/questions/13905200/), while enables `-Wextra`. Otherwise they distract those who read build logs from real warnings.
=> Remove useless warnings in Travis clang builds

plugins/DebuggerCore/unix/linux/PlatformState.cpp
gcc makes it harder to catch these types of problems, while with clang, even though build succeeds, DebuggerCore fails to load due to missing symbols.
=> Add missing instance of orig?AXName outside of class scope

plugins/DebuggerCore/DebuggerCore.pro, plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, plugins/DebuggerCore/unix/linux/detect/proc-pid-mem-write.cpp
This fixes #304. The only thing I'm not sure of is whether there's a way to run detection at the stage of `qmake` itself instead of as a separate build target.
There's [`system()`](http://qt-project.org/doc/qt-4.8/qmake-function-reference.html#system-command) command, but using it correctly would require doing some tricks in the header generator to detect whether the header has to be touched, otherwise running `make` twice will rebuild `PlatformProcess.cpp` twice.
=> Fix memory writes on systems with broken /proc/pid/mem write access

plugins/DebuggerCore/DebuggerCore.pro, plugins/DebuggerCore/unix/linux/detect/proc-pid-mem-write.cpp
The first commit `$$QMAKE_LFLAGS` to compilation commands of the broken kernel detector. I've come across a problem when clang (on my system) requires additional LDFLAGS to be able to locate some of the libs for every app it builds.
And the second one removes unused variables, thus silencing clang.
=> Minor clang fixes

plugins/BinaryInfo/symbols.cpp
Demangled symbols can get much larger than 256 characters in length. And `qsnprintf` shouldn't be used in any case, so this just switches to `QString::arg()`.
=> Don't use fixed-size buffers to format symbol names

src/widgets/RegisterViewDelegate.cpp, src/widgets/RegisterViewDelegate.h
Currently `RegisterViewDelegate` is based on `QItemDeletage`, which makes register view look not fully styled. Namely, with Oxygen, we lose hover effect and all those non-flat selection rectangles.
Default `QTreeView` and similar views install `QStyledItemDelegate` as their renderers. So `RegisterViewDelegate` should actually be based on it to make untouched rows look correct.
BTW, do you think it'd be a good idea to use `QStyle::drawPrimitive()` for disassembly, stack and hex views, so that they allowed hover effects and styled selections?
=> Use QStyledItemDelegate as base for RegisterViewDelegate

include/string_hash.h
The default argument `n=N` makes the first shift `..<<(8*(n-1))` result in UB when `N==9` (i.e. string with maximum length of 8), since the RHS evaluates to 64, equal to number of bits in `uint64_t`. This commit fixes it to start from `n=N-1`: the last character is the NULL terminator anyway, so no point in processing it.
=> Fix UB in string_hash<9> due to left shift by 64

src/Debugger.cpp, src/DialogOpenProgram.cpp, src/DialogOpenProgram.h, src/src.pro
This clones the functionality present in OllyDbg's file open dialog. OllyDbg seems to do some ugly-looking hack on the stock Win32 dialog, so that the entries are misaligned with the stock ones. This attempt tries to use QFileDialog's layout to align the labels and entries so that the result looks much better.
A downside of this feature is that we no longer have native dialogs since Qt4+ doesn't allow us to add custom widgets using the official API.
Another downside is that no one guarantees that the layout will always be as it is. OTOH, I see no reasons why they would suddenly change it, and the code does sanity check the dialog's layout and refrains from modifying if it looks suspiciously.
=> Let the user enter program arguments and working dir in file open dialog

plugins/HardwareBreakpoints/HardwareBreakpoints.cpp, plugins/HardwareBreakpoints/libHardwareBreakpoints.cpp
This fixes incorrect assertion condition, and additionally clearifies error message about BP alignment.
=> Fix HW BP setting in case of 8-byte reads and writes

plugins/DebuggerCore/unix/linux/detect/proc-pid-mem-write.cpp, src/DialogOpenProgram.cpp
In some cases build stalls due to infinitely sleeping `proc-pid-mem-write`. This seems to be due to forgetting to kill child. I don't quite understand what exactly happened there, but this is clearly a bug which should be fixed. And it does seem to fix those stalls.
=> Fix leaking forked child

plugins/Assembler/CMakeLists.txt, src/CMakeLists.txt
Don't know whether it does work with CMake 3, but with 2.8 I found that the current instruction arrow in disassembly view was missing, and list of assemblers in plugin settings was empty and disabled. This commit fixes adding Qt resources with CMake 2.8.
=> Fix adding of resources with CMake 2.8

plugins/SymbolViewer/DialogSymbolViewer.cpp
This addresses #340. In fact it appeared that most of the slowliness was due to debug build of Qt. Still, this commit makes even debug Qt more than an order of magnitude faster to render the list after the model is set.
=> Improve rendering performance of SymbolViewer's list

include/Configuration.h, include/IDebugEvent.h, plugins/DebuggerCore/unix/linux/PlatformEvent.cpp, src/Configuration.cpp, src/Debugger.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/edb.cpp
This makes it possible to have behavior more similar to that of OllyDbg regarding signals.
I'm not sure though whether such prefixes as `SIGSEGV: SEGV_ACCERR: ` are a good idea for status bar. Maybe they are better shown only for some ambiguous signals when we can't say their exact reason (e.g. `SIGSEGV` with `code==128`).
=> Show signals in status bar, let the user disable signal message boxes

src/widgets/QDisassemblyView.cpp
This uses larger arrows to show directions of jumps. The original ones are too tiny to see even on small-resolution monitors.
After this change the down arrow also appears at the bottom of the line instead of top, which further improves differentiation between the two.
=> Use more visible arrows to denote jump directions

plugins/Assembler/DialogAssembler.cpp, plugins/Assembler/xml/assemblers.xml, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h, src/widgets/SyntaxHighlighter.cpp
These commits
1. fix a bug with determining operand count in the case of long jmp/call instructions
2. Add fasm to the list of supported assemblers
3. Change size specifiers like `dword ptr` to more making sense like `dword` (so that the syntax now matches that of the three supported assemblers more closely)
4. Remove size specifiers in cases when operand size is unambiguous, e.g. `mov eax,[ecx]`.
=> Some changes in (dis)assembly

src/arch/x86-generic/ArchProcessor.cpp
It looks quite silly when EDB says "... = 5 (decimal)".
=> Don't mention that a value is decimal if it's unambiguous

src/arch/x86-generic/ArchProcessor.cpp
Currently EDB crashes when it encounters an instruction with VSIB addressing, e.g.
C4 E2 65 93 8C 79 99 33 55 00   vgatherqps xmm1,dword [ecx+ymm7*2+0x553399],xmm3
First commit works around this, leaving addition of VSIB support as a TODO.
Second commit prevents senseless calculations when e.g. VSIB has `ymmN` as index while the CPU/OS doesn't support AVX.
=> Check that index register is a GPR, otherwise EDB'd crash. 

src/capstone-edb/Instruction.cpp
This operand type may go away in a future version of capstone (see https://github.com/aquynh/capstone/issues/648), so better be prepared for this.
This might create a compiler warning about not all the cases handled in the switch, but I think we could tolerate it temporarily, rather than add a default case.
Another commit here fixes an unrelated warning, which still could hide some more useful warnings of its type.
=> Remove mentioning of X86_OP_FP

include/Register.h, src/arch/x86-generic/ArchProcessor.cpp, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h
This enables quick analysis view display floating-point operands of SIMD instructions in more useful format. E.g. if you have an instruction like
vrcpss xmm3,xmm7, dword [esp]
you'll have the following lines in quick analysis view:
xmm7={124.352, 972e+3, 0.0, -5.23526}
xmm3={0.0,0.0,-0.0,1.3}
dword [esp] = [0xffe3ce50] = 1.40129846e-45
according to the types of the operands (here xmm7 and xmm3 are packed single-precision, while `[esp]` is scalar single-precision floating-point numbers).
Also FPU BCD operands are now formatted according to BCD format too.
=> SIMD floating-point operands formatting

plugins/DebuggerCore/unix/linux/PlatformState.cpp
This "shouldn't happen" appears to actually sometimes happen, so we do need more detail in debug print.
=> Print actual unexpected size

plugins/BinaryInfo/symbols.cpp
Ubuntu (and likely Debian) don't have a `.debug` suffix in debuginfo filenames, so this adds support for such a scheme.
=> Add support for Ubuntu naming convention of separate debuginfos

include/BinaryString.h, include/edb.h, src/BinaryString.cpp, src/BinaryString.ui, src/Debugger.cpp, src/edb.cpp
This commit makes it possible to enter a binary string longer than selected bytes string. It follows the same idea as Assemble dialog: presents a "keep size" checkbox.
The old mode of length-limited entry is retained to leave the interface of `get_binary_string_from_user` the same, although both places where this function is used don't use this mode. In this mode the checkbox is hidden, and length limit is enforced to be equal to the supplied one — instead of being equal to initial value length.
There's also a comment regarding "set length before value", which you can later delete if you find that the comment it references is invalid.
=> Let the user write binary string longer than selected bytes

plugins/ODbgRegisterView/GPREdit.cpp
That is a simple typo leading to user confusion.
=> Fix reading 64-bit values with high bit set

src/Debugger.cpp, src/edb.cpp
`processEvents()` appears to take quite a bit of performance away from EDB (especially visible on my EEE PC with Intel Atom).
This commit uses the least necessary action to make sure the status is repainted, so as to avoid too much time spent uselessly.
=> Avoid processing all events just to repaint the status bar.

plugins/DebuggerCore/unix/DebuggerCoreUNIX.cpp
Otherwise, when a file can't be executed (e.g. ELF64 on 32 bit kernel or corrupted file) we get shell as a debuggee, which is very confusing.
The functionality we lose here was not used in EDB anyway, since it appears to check existence of the file before calling `execute_process()`, so this function never got any opportunity to search in `$PATH`.
As a bonus, we can now run files in current directory like `edb --run filename`, not necessarily as it was before: `edb --run ./filename`. New behavior is much more consistent than requiring a slash in file path but not searching in `$PATH` when no slash is present.
=> Use execv instead of execvp.

plugins/Assembler/DialogAssembler.cpp, plugins/Assembler/xml/assemblers.xml
This adds support for GAS with Intel and AT&T syntax (so EDB can now assemble in AT&T syntax).
Also, now instead of "normalization" of user input (which does break for GAS due to stripping of ` ptr`), it does a fixup of operand size names of the _initial instruction_ to the format expected by active assembler.
No attempt is done to fixup instruction mnemonics currently, so e.g. `lcall` will not work out of the box for fasm, which expects `call far` instead.
=> Improve assemblers support, add a new one

src/BinaryString.cpp
Binary string is almost always used to enter hex data, not text. This also matches the defaults of OllyDbg.
=> Set focus to hex entry by default in binary string editor.

include/Configuration.h, include/ISymbolManager.h, src/Configuration.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/SymbolManager.cpp, src/SymbolManager.h, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h, src/widgets/QDisassemblyView.cpp
This adds some options for instruction formatting
1. Alignment of operands (tab-like; two tab stops for short and long instructions)
2. Avoiding extraneous display of local module names in jump/call targets (e.g. `<_dl_start>` instead of `<ld-2.14.1.so!_dl_start>` when called from within `ld-2.14.1.so`)
3. Transformation of `[rip+0xd1521ace]` into `[rel 0xad7e55]`.
=> New options for instruction formatting

plugins/Assembler/xml/assemblers.xml
GAS appears to be quite quirky. The first of these commits fixes my minor mistake, but the second fixes a major problem with usage of older versions of binutils. See commit message for details.
=> Some fixes of GAS usage

include/Configuration.h, include/IDebugger.h, plugins/DebuggerCore/DebuggerCoreBase.cpp, plugins/DebuggerCore/DebuggerCoreBase.h, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, src/Debugger.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/lang/edb_en.ts
This fixes #377 and adds a third option of close behavior: kill if launched, detach if attached.
=> Detach and kill

include/Configuration.h, plugins/BinaryInfo/symbols.cpp, src/Configuration.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/widgets/QDisassemblyView.cpp
This adds an option to see call/jump targets symbolically, like `call _dl_start` instead of `call 0xf76f8160 <_dl_start>`. Also, instead of `jmp $sym_0x080486d0` we'll now see something more like `jmp .plt`, since unnamed symbols are now named according to the name of the section they are in.
=> Show better symbolic addresses

src/widgets/QDisassemblyView.cpp
See the commit messages. In short, one commit improves backwards scrolling experience by making it less jumpy, and another one makes it possible to scroll per-byte to precisely choose starting address of disassembly.
=> Some improvements of disassembly scrolling

src/widgets/QDisassemblyView.cpp
We use this function to avoid filename prefix when it's not needed. But the same file may have multiple regions, e.g. .text and .data. This doesn't make the reference from code to data non-local, since the prefix would be the same. So it's more correct to compare region names.
This will make a difference if/when EDB is able to show data references in symbolic form too.
=> Fix comparison of regions to determine whether target is local

plugins/DebuggerCore/unix/linux/PlatformCommon.cpp, plugins/DebuggerCore/unix/linux/PlatformCommon.h
It doesn't make sense to use `long` in code intended to support both 64-bit and 32-bit debuggees, since its size depends on debugger itself.
This fixes #389.
=> Fix reading user stat for 64-bit processes in 32-bit EDB

src/widgets/QDisassemblyView.cpp
Otherwise we have still inverted color even when selection becomes duller, which is wrong (cf. treeviews behavior).
=> Fix choice of highlighted text color to take focused state into account

src/capstone-edb/Instruction.cpp
Otherwise EDB will assertion-fail when trying to format `lcall` or `ljmp` disassembly.
=> Add missing operand push_back

plugins/Assembler/DialogAssembler.cpp
Otherwise we get funny effects if we try to reassemble the stupid mnemonic capstone gives for `popad` (it gives `popal`, which few if any assemblers understand).
=> Give error on zero-sized output of an assembler

src/arch/x86-generic/ArchProcessor.cpp
EDB currently says that `write` syscall will be restarted, even if it merely finished returning 15 (bytes written). The first commit fixes this. The second makes EDB also report just-ended syscalls.
=> Syscall analysis fixes

include/IDebugger.h, plugins/Analyzer/Analyzer.cpp, plugins/Backtrace/DialogBacktrace.cpp, plugins/BinaryInfo/DialogHeader.cpp, plugins/BinarySearcher/DialogASCIIString.cpp, plugins/BreakpointManager/DialogBreakpoints.cpp, plugins/CheckVersion/CheckVersion.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, plugins/DebuggerCore/unix/linux/PlatformRegion.cpp, plugins/FunctionFinder/DialogFunctions.cpp, plugins/HardwareBreakpoints/HardwareBreakpoints.cpp, plugins/HeapAnalyzer/DialogHeap.cpp, plugins/OpcodeSearcher/DialogOpcodes.cpp, plugins/ProcessProperties/DialogStrings.cpp, plugins/ROPTool/DialogROPTool.cpp, src/Debugger.cpp, src/edb.cpp
First commit removes explicit check for existence of the file to run, allowing `execv()` to report exact errors instead of blurry "please check privileges".
Second commit switches the error message boxes to real errors (and warnings to real warnings) instead of information. This makes the type of message immediately obvious to the user by its icon (and maybe sound).
Third one gives the exact errors for `attach()` similarly to already done `open()`.
=> Some improvements to error messages 

src/widgets/QDisassemblyView.cpp
Otherwise we have bad readability due to low contrast. I don't have better ideas than to disable syntax highlighting for selected line. See the comparison:
=> RFC: Only syntax-highlight disassembly if the instruction isn't selected

include/Configuration.h, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, src/Configuration.cpp, src/DialogOptions.cpp, src/DialogOptions.ui
This adds some options which are often helpful when debugging often-restarted programs: to disable ASLR and to disable lazy binding of dynamically linked functions.
=> Add some helpful debugging options

src/arch/x86-generic/ArchProcessor.cpp
I was mistaken that error return values can't be `>UINT32_MAX`. They actually can, I should have looked in the other file in glibc source.
=> Fix detection of error code in syscall return value for 64 bit debuggee

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
It's defined in <linux/ptrace.h> instead of <sys/ptrace.h>, but the former lacks some defines like PTRACE_PEEKUSER and also conflicts with the latter. So it's better to just copy-paste the definition of the constant.
=> Fix usage of PTRACE_O_EXITKILL

include/FloatX.h, plugins/ODbgRegisterView/GPREdit.cpp, src/RegisterViewModelBase.cpp
When compiling edb today, with Debian's "gcc version 5.3.1 20160509 (Debian 5.3.1-19)", I got several errors like "/home/.../edb-debugger/include/FloatX.h:50:57: error: ‘log10’ is not a member of ‘std’".  These stemmed from header files not being included in three specific files.  So, I included them, it compiles and runs, maybe this'll be useful for others.
Not sure why I'm having trouble, when these files don't ever seem to have been included...
My first guess was that my g++ command line was wrong, but it seemed to be correct.  Here it is anyway, for reference, "g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui …
=> Include Mandatory Header Files

plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
It's supported only since Linux 3.8, so no sense to abort the whole debug session if it failed to be set.
=> Don't consider failure to set PTRACE_O_EXITKILL fatal

plugins/DebuggerCore/Breakpoint.cpp
This fixes #431. Also, if the breakpoint fails to even read the byte, it'll now return `0xff` as original byte instead of a random value.
=> Return valid original byte for a failed-to-write breakpoint

src/graph/GraphNode.cpp, src/graph/GraphWidget.cpp
`<cmath>` includes were missing from `GraphNode.cpp` and `GraphWidget.cpp` in `src/graph`
also fixed a missing `std::` in `GraphNode.cpp`
Both of these issues were breaking the build.
=> Fixed missing std:: qualifier, and cmath includes in graph source.

src/capstone-edb/Instruction.cpp
Otherwise we have compilation failure.
=> Remove enum entry which is not present in Capstone 4 and was never used in Capstone 3

.travis.yml
Build and upload an [AppImage](http://appimage.org/) for Qt 5.6 builds (builds prior to  Qt 5.5 are not yet bundled correctly due to what I suspect to be a [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) bug). The URL of the built AppImage can be seen in the build log.
=> Build and upload AppImage

src/CMakeLists.txt, src/Debugger.cpp, src/widgets/NavigationHistory.cpp, src/widgets/NavigationHistory.h, src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
Saves the last 100(customizable) movements.
Keys for navigation: Enter, Plus, Minus.
Fix scroll up/down to navigate the lines
=> Add navigation history for CPU view

plugins/DebuggerCore/unix/linux/PlatformProcess.cpp
This is a correction of a small bug which caused the file paths with spaces (parsed from map files) to be truncated (before the first space).
=> Correctly handle whitespace in file paths in map files

src/CMakeLists.txt, src/ExpressionDialog.cpp, src/ExpressionDialog.h, src/edb.cpp
Fixes #466.
The expression dialog will now gray out the OK button if the expression is not valid, and will display the error message for the expression in red underneath the text entry field. This gives immediate feedback that the expression is wrong before the user closes the window. This is much better than the previous flow which interrupted the user with a dialog box and then closed the window when they made a mistake.
Even though I got the clipboard feature working that I described in my original issue, I decided it wasn't a good idea; it would be better to instead improve on the Goto dialog to include a history of the last X items the user has searched for which is closer to what the gold standard Ollydbg does.
=> Improve the UX of get_expression_from_user

README.md
Just a simple fix for the README, previous command gave the following error:
```
$ git clone --recursive git@github.com:eteran/edb-debugger.git
Cloning into 'edb-debugger'...
Warning: Permanently added the RSA host key for IP address 'xxxx' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
Fixed with:
`git clone --recursive https://github.com/eteran/edb-debugger.git`
Now everyone should be able to clone.
=> Fix git clone link

plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, plugins/DebuggerCore/unix/linux/PlatformProcess.h
This fixes the infuriating issue where it was impossible to add breakpoints, remove breakpoints or edit the dump while a debuggee was running. This was caused by both read_bytes and write_bytes putting single byte read/writes (one of each is necessary to make a breakpoint) on a so-called "fast path" which tries to avoid /proc/<pid>/mem.
While fixing this issue I decided this code was a little too "patch-fixy" for me. It looks like we patched in /proc reading to fix limitations occasionally but were not consistent in where we applied these patches. As a result we sometimes we check /proc, sometimes we check ptrace, and sometimes we do both. I decided to refactor the area so that /proc always comes first followed by ptrace, and I renamed each method to more clearly indicate its …
=> Always use /proc/<pid>/mem over ptrace whenever possible

plugins/DebuggerCore/unix/linux/PlatformCommon.cpp
This fixes an issue where my executable named "test2.5" would fail to have any entrypoint detected for it at all. Turns out this was because the parsing of /proc/<pid>/stat was failing its match expression which has a whitelist of sane characters to expect.
I don't feel like this whitelist is a good idea because  binaries can have any name in unix as long as it doesn't contain a NUL or / character. But I'll do the cheap and easy fix for my case instead.
=> Fix /proc/<pid>/stat parse failure when binary name has .

src/widgets/QDisassemblyView.cpp
This patch-set annotates constants in the disassembly screen which appear to point to ASCII strings.
An unfortunate limitation of my patchset is that it does not understand the constants inside relative expressions. This appears common on x64 targets. Here's a simple hello world showing that the two LEAs that are RIP-relative are not annotated:
If anyone has any ideas how I can fix this corner case, I'm all ears.
=> Annotate constants in disassembly if they appear to point to ASCII

plugins/Analyzer/AnalyzerWidget.cpp
* No longer display "No Analysis for This Region" if region is not valid (such as before any debugee has been launched)
* Change "No Analysis For This Region" to instead say "[libname]: No Analysis Found" which might make it easier to understand why Analysis disappeared while stepping through code that invokes another library.
=> Change Analysis Bar message

plugins/BinaryInfo/PE32.cpp, plugins/BinaryInfo/PE32.h, src/edb.cpp
I'm not sure if this is enough to actually be able to run edb on windows, but this does successfully decode the header of a 32bit windows application running under wine on my machine.
I also removed a debug string I had added because it was never actually triggering before because every single region that should have had no binary at all was instead being picked up as PE32 since it had no sanity checks at all.
=> Implement bare minimum PE32

plugins/Analyzer/Analyzer.cpp
Fixes #488
Basic blocks was calling `will_return` frequently which was doing a linear search through the symbols map when a faster map lookup was available. Changing this reduced my analysis time to 20 seconds (from 170).
=> Improve Analysis ("Basic blocks") Performance

plugins/BinaryInfo/ELF32.cpp, plugins/BinaryInfo/ELF64.cpp, plugins/BinaryInfo/ELFXX.cpp, plugins/BinaryInfo/ELFXX.h, plugins/BinarySearcher/DialogBinaryString.cpp
This mainly fixes this issue:
https://github.com/eteran/edb-debugger/pull/489#pullrequestreview-11279382
and also fixes some redundant semicolons I have littered in the BinaryInfo plugin.
=> Fix bug in binary search window +minor style fix

include/IAnalyzer.h, include/edb.h, plugins/Analyzer/Analyzer.cpp, plugins/Analyzer/Analyzer.h, src/debugger.qrc, src/edb.cpp, src/images/arrow-right-red.svg, src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
So I rewrote the disassembler paint event. My rewrite of the paint event code is somewhat opinionated but I think it might be better. Its structure lets us perform more high-level analysis when painting stuff (we can look at all of the disassembled instructions at once during one render pass) which might be useful if we decide to start painting more details someday.
To test my changes I inserted QElapsedTimer into the paintEvent and judged the elapsed time. My changeset doesn't result in an amazing speedup when analysis isn't working (maybe 6ms instead of 7ms? nothing amazing), but after analysis, in my massive debuggee binary, my paint times go from ~500ms to 6ms! I did this by adding a new method to the Analyzer which returns all functions that exist between a particular range of …
=> Disassembly paint rewrite

src/widgets/QDisassemblyView.cpp
Fixes #494 
This makes all of the function analysis lines disappear when the font is too small since `painter.drawLine` doesn't appear to have a clip feature.
=> Fix certain clipping issues when l2 close to l3

src/widgets/QDisassemblyView.cpp
We were painting the background color for selected lines at the wrong time, causing them to paint over the symbol names.
=> Fix symbols disappearing when on selected line

include/Configuration.h, src/Configuration.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
This adds register badges as described in #486 
* I look for both registers and the values pointed to by registers. The latter might not be very useful but I don't think it hurts anything.
* If multiple registers point to the same place we append the strings together (badge says `eax, ebx`. this will definitely make us paint over the addresses, though. 
* They are always white text on blue background. We should probably figure out how we can use the palette to make these badges themeable instead.
* I changed the line1/line2/line3 resize code so that if the user moves the mouse quickly, instead of ignoring the resize, we resize to the minimum.
=> Reg badges

include/IAnalyzer.h, plugins/Analyzer/Analyzer.cpp, plugins/Analyzer/Analyzer.h, src/widgets/QDisassemblyView.cpp
@eteran implemented a hint API on the Analyzer after I suggested it might make the analyzer function lookups faster, and it probably did. However, experience has taught us well, and now we know that `QMap::upperBound` could have been used instead as a much faster way to find the exact entry we were looking for thanks to the fact QMap uses skip lists. So I undid most of that work we did and replaced `find_containing_function`'s iteration with `upperBound` usage. I've tested for correctness but not performance, but I think we can all agree it is hard to imagine performance being any worse after this.
=> Remove "hinted" lookups from (I)Analyzer

plugins/BinaryInfo/ELF64.cpp
If the gcc application entrypoint stub appears after the main in memory, gcc generates a RIP-relative instruction that is negative. Our heuristic code would treat the rel as unsigned resulting in the breakpoint not being placed.
=> Fix main heuristic failing when rel is negative

plugins/Assembler/Assembler.cpp, src/Debugger.cpp, src/Debugger.h
* Added ellipsis to menu entries that open new windows
* Grouped all edit operations together under one menu and placed it at the top of the context menu
* Removed "Remove Breakpoint" and "Remove Comment" options since the former can be done with the Toggle option just as easily and the latter basically never happens and can be done with the menu instead.
Old:
===
New:
===
Work left to do:
===
* Change plugin interface so that plugins can insert menu items in arbitrary positions and arbitrary submenus. This is necessary to be able to move the Assemble command toward the top of the context menu instead of it being stuck at the bottom, and to move hardware breakpoint options into a submenu with the regular breakpoint options.
* The Analyzer plugin's "Goto Function Start/End" features should …
=> Tweaks to Context Menu to be more like Ollydbg

plugins/FunctionFinder/DialogFunctions.cpp
The function finder would refuse to graph any function that did not have a symbol. This is because `QTableWidget::selectedItems` only returns items which have content. This would cause the `items.size() == ui->tableWidget->columnCount()` test to fail whenever any cell was empty (i.e. no symbol).
=> Fix graph feature failure if func has no symbol

plugins/DebuggerCore/unix/linux/PlatformCommon.cpp
I am on a roll today (fixing bugs that I introduced)!
It looks like the meaning of the hyphen character is position-dependent: when I added the dot character to the scanf expression a few weeks ago, I added it adjacent to the hyphen which apparently changed its meaning to a range, which did not include the hyphen. This caused an infinite loop when trying to attach to a process which had a parent process whose name had hyphens in it. I am not entirely sure what the deal with that was.
=> Fix processes with hyphens failing get_user_stat

include/Function.h, src/Function.cpp
We have a variable in `Function` that is only written to, never read from. This PR removes it.
@eteran what was the intended use of this variable? It's definitely not in use anymore. It also makes the constructor that takes an address dangerously misleading since the address isn't actually used for anything.
=> Remove redundant variable from Function

plugins/Analyzer/Analyzer.cpp, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h
So it turns out that capstone-edb was string-formatting instructions in the `Instruction` constructor, even if the consumer of the instructions had no intention of ever using those strings for anything. By moving this string formatting into the Formatter (where it probably should have always been), we can improve performance for those use cases.
Notably, in my tests, this improves analysis performance by about *3.7x*.
```
[Analyzer] elapsed: 117828 ms
[Analyzer] elapsed: 31546 ms
```
=> Analysis improvements

src/widgets/QDisassemblyView.cpp
I recommend viewing the diff with ?w=1 at the end of the URL to ignore whitespace.
This changeset makes it so that using the arrow keys to navigate within the current viewport does not need to call previous_instruction or forward_instruction.
It also makes it so that using the arrow keys to navigate downward past the viewport's bottom no longer causes the viewport view to shift down by a whole page; now we only scroll down 1/3rd of the viewport. This makes it less likely to get lost. This still isn't as great as I'd like it to be, but this will have to do for now since making it scroll the viewport down one instruction seems to have issues relating to instructions that were disassembled incorrectly.
=> Improve arrow-key selection navigation somewhat

plugins/Analyzer/AnalyzerWidget.cpp, plugins/Analyzer/AnalyzerWidget.h
When there are a HUGE number of functions the analysis bar can take up to 35ms to paint on my machine. Since the analysis bar looks exactly the same on basically every render, we instead paint the base analysis bar onto a buffer and cache it. Then, if none of the dimensions or number of functions have changed, we blit the buffer back and then paint the yellow triangle "You are here" indicator over the buffer.
This dramatically improves the performance of the Analyzer bar paint event which now takes 1ms. When combined with my other pull request, I finally get full frame rates while scrolling around in edb after my binary has been analyzed.
=> Cache analysis bar paint results

src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
This improves rendering performance pretty significantly when scrolling around and clicking on stuff without jumping the viewport around a lot.
My paint times on my beefy machine went from 8-13ms to 2-3ms when the cache was getting hit consistently. This effectively eliminates a lot of the extra CPU cost of using syntax highlighting vs not using it. This reduced paint time also means that weaker machines will be more likely to keep up with 60fps (one frame every 16ms).
=> Cache Syntax Highlighting results

plugins/Analyzer/AnalyzerWidget.cpp
Forgot to initialize the `QPixmap* cache_` polnter to `nullptr`. It must not have crashed on my system because of a different memory allocator, but when I tried on my laptop running an older debian it crashed quickly.
=> Fix segfault in Analyzer Widget

src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
@eteran can you try this version? It looks like all we had to do extra was copy the `devicePixelRatio` of the parent widget.
It would be nice if there was a way to automatically copy these attributes of the parent widget...
=> Cache syntax highlighting

plugins/Analyzer/Analyzer.cpp
Only occurs in debug builds. Harmless.
=> Fix index out of range assertion failure

include/Expression.tcc
This change makes quoted expressions tokenized as a single variable.
Fixes #400.
Note that this does not make any changes to the expression dialog's auto-completion. After activating an entry in its auto-completer it will immediately say "Invalid Expression" afterward. I wanted to fix this, but I don't see any good ways. Adding quotes around all symbols that have spaces will make them harder to find with the auto-completer. Ideally we would quote variables as they are inserted, but I don't see any clear and obvious correct way of doing that.
=> Allow quoting variables in expressions

.gitmodules
This is good for people behind an http proxy who want to install the debugger from source.
The git based url requires SSH access which is not possible over http/s proxies usually.
=> Change qjson4 url to https instead of git

src/widgets/QDisassemblyView.cpp
Currently disassembly unconditionally moves 10 down on PageDown press, and some number of lines  ≤10 up on PageUp press. These commits make it respect its height, as well as fix a bug in `QDisassemblyView::previous_instructions()` logic (although it still doesn't give exactly the requested count of previous instructions, but now it's much closer). Also Ctlr+Up/Down now do the same thing as Ctrl+Wheel, thus allowing the user to have less need in a mouse.
=> Fix disassembly view page up/down behavior

src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
`line1`, `line2` and `line3` indicators are now relative to the new `line0` which represents space allocated on the leftmost part of the widget rendering area for various extras (for now, just the register badges).
Fixes #552.
=> Resize 0->l1 area size to contain address badge

plugins/DebuggerCore/unix/linux/PlatformState.cpp
RSP isn't a frame pointer register on x86(_64), RBP is.
=> Return RBP as frame pointer register

plugins/ODbgRegisterView/CMakeLists.txt, plugins/ODbgRegisterView/DialogEditFPU.cpp, plugins/ODbgRegisterView/DialogEditFPU.h, plugins/ODbgRegisterView/DialogEditGPR.cpp, plugins/ODbgRegisterView/DialogEditGPR.h, plugins/ODbgRegisterView/DialogEditSIMDRegister.cpp, plugins/ODbgRegisterView/DialogEditSIMDRegister.h, plugins/ODbgRegisterView/EntryGridKeyUpDownEventFilter.cpp, plugins/ODbgRegisterView/EntryGridKeyUpDownEventFilter.h
Otherwise it's very inconvenient to use e.g. SIMD register editor when you want to e.g. move focus from float64 entry to integer byte.
=> Let the user use Up/Down arrow keys to go to upper/lower entries in the registry editors

plugins/ODbgRegisterView/EntryGridKeyUpDownEventFilter.cpp
This way the contents of the new cell are selected as if we pressed Tab while being in a cell to the left of the new one. This makes navigation consistent between Tab/Shift-Tab/Up/Down directions.
=> Make the entries think they were tabbed into Up/Down arrows

include/arch/arm-generic/ArchDefs.h, include/arch/x86-generic/ArchDefs.h, include/arch/x86-generic/ArchTypes.h, plugins/InstructionInspector/Plugin.cpp, plugins/OpcodeSearcher/DialogOpcodes.cpp, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Instruction.h, src/capstone-edb/include/Operand.h
This mostly makes InstructionInspector at least start on ARM. Also Instruction class is now a bit more ARM-aware. Also, OpcodeSearcher at least now compiles (added missing `STACK_REG`).
There's still some work to do in each of these, but these commits are self-sufficient, so to avoid potential conflicts with your work I request merge.
=> A bit more ARM-related fixes

include/IDebugger.h, include/IProcess.h, include/IThread.h, include/Status.h, plugins/DebuggerCore/CMakeLists.txt, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/DebuggerCore.h, plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, plugins/DebuggerCore/unix/linux/PlatformProcess.h, plugins/DebuggerCore/unix/linux/PlatformThread.cpp, plugins/DebuggerCore/unix/linux/PlatformThread.h, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformThread.cpp, plugins/DebuggerCore/unix/linux/arch/x86-generic/PlatformThread.cpp, src/Debugger.cpp
This brings a bit of robustness to the API, as well as to the implementation of Linux-specific parts of DebuggerCore and Debugger itself.
There're still some things to improve: namely, menus change to running state simply when no errors in "continue"/"step" etc. occur. I'd rather have Debugger query DebuggerCore for actual state, and set GUI state based on this. This would make it even more robust. But this seems to require further changes to IDebugger, which I think had better go to another set of commits.
This set of commits also fixes #579.
=> Make most IDebugger and related methods return Status instead of void

plugins/DebuggerCore/unix/linux/PlatformProcess.cpp
I'm not sure though: what is supposed to be done if the status is `DEBUG_STOP`? Is returning OK status the correct action?
=> Add missing return statement.

include/IProcess.h, plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, plugins/DebuggerCore/unix/linux/PlatformProcess.h, src/DialogAttach.cpp, src/DialogAttach.h, src/DialogAttach.ui, src/DialogThreads.cpp
This makes some usability improvement in DialogAttach as well as DialogThreads. Now it's possible to switch current thread. The latter improvement fixes #347.
=> Some UX improvements

include/IBreakpoint.h, plugins/DebuggerCore/arch/arm-generic/Breakpoint.cpp, plugins/DebuggerCore/arch/arm-generic/Breakpoint.h, plugins/DebuggerCore/arch/x86-generic/Breakpoint.h, plugins/DebuggerCore/unix/linux/PlatformProcess.cpp, src/Debugger.cpp
Although single-stepping doesn't currently work (and will require the same mechanism as in Step Over feature, which currently doesn't work too :) ) due to [this kernel patch](http://lists.infradead.org/pipermail/linux-arm-kernel/2011-February/041324.html), now EDB can at least "run to cursor" repeatedly, and the breakpoints are not shown as garbled code. Also, the breakpoints now result in SIGTRAP instead of SIGILL, which makes it easier to handle them (fewer changes WRT x86).
=> Fixes to ARM breakpoints

include/Configuration.h, include/IBreakpoint.h, include/IDebugger.h, include/Types.h, include/Util.h, include/edb.h, plugins/DebuggerCore/DebuggerCoreBase.cpp, plugins/DebuggerCore/DebuggerCoreBase.h, plugins/DebuggerCore/arch/arm-generic/Breakpoint.cpp, plugins/DebuggerCore/arch/arm-generic/Breakpoint.h, plugins/DebuggerCore/arch/x86-generic/Breakpoint.cpp, plugins/DebuggerCore/arch/x86-generic/Breakpoint.h, plugins/DebuggerCore/unix/linux/DebuggerCore.cpp, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformState.cpp, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformState.h, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformThread.cpp, src/Configuration.cpp, src/Debugger.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/capstone-edb/Instruction.cpp, src/edb.cpp
Summary:
* Now it's possible to choose from a bunch of breakpoint types for both x86 and ARM targets. This mostly works, but if the breakpoint used generates something other than `SIGTRAP`, EDB doesn't yet remove it, even if it's a single-shot breakpoint, and notifies of the signal, which it shouldn't.
* It's now possible to set registers, not only view them. Register editor on ARM still presents somewhat wrong edit dialogs, inherited from x86 version.
* `BX` and `BLX` instructions are now supported for single-stepping.
=> Varying breakpoint types, changing thread state, more complete single-stepping

plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformThread.cpp, src/arch/arm-generic/ArchProcessor.cpp, src/capstone-edb/Instruction.cpp
The original code appears to have been wrong. Additionally, there's a bug in capstone, for which I added a work around.
=> Fix calculation of scaled-register-offset memory operands

appveyor.yml, plugins/DebuggerCore/win32/DebuggerCore.cpp
This enables building an x86 version of EDB and the DebuggerCore plugin on Windows with CMake and Visual Studio 2017 (AppVeyor uses Visual Studio 2015 since Qt 5.9.1 x86 is not available in the Visual Studio 2017 image).
Note: The functionality of the plugin is far from complete, but the existing code compiles again.
=> EDB and DebuggerCore on Windows x86 with MSVC

src/CMakeLists.txt, src/Configuration.cpp
The default plugin path is invalid when it embeds other macros like i386.
This was already reported in #134.
To avoid this problem, we define the DEFAULT_PLUGIN_PATH macro as a quoted string ready to be used in the code (the STRINGIFY trick is thus no-longer needed).
Kali bug: https://bugs.kali.org/view.php?id=4265
=> Fix default plugin path

src/arch/x86-generic/ArchProcessor.cpp, src/xml/syscalls.xml
This changeset makes all the syscalls listed in the XML printed with parameters. It also adds support for x32 syscalls and adds some which appeared in newer versions of Linux. Thus this fixes #425 and #194.
Also, all integers formatted in `format_integer` are now in hex, since it makes more sense unless we know what exactly they represent.
I do have generated these XML entries by my quick and dirty tool, but currently it's too dirty to be put into EDB. Also, I don't quite like that I have to manually fixup some syscalls which aren't present in Linux's `syscalls.h`, so this is another reason to avoid putting it to the EDB source tree.
I can provide the sources for it if you really want though (maybe by email or whatever). But in the longer-term perspective I'd like to make some library out …
=> Add parameters to all syscalls in the list

src/DialogMemoryRegions.cpp
If a region appears to be a code region, show it in the CPU view when double-clicked instead of the data-dump view.
=> Mem Regions window: dblclick shows in CPU if --x

src/Debugger.cpp, src/Debugger.h
=> Fix stepping instruction following a breakpoint covering a same-size instruction

appveyor.yml, include/Types.h, src/CMakeLists.txt, src/FloatX.cpp, src/LongDoubleX86.asm
Windows does not support 80bit long doubles natively. Instead a long double is equivalent to the 64bit double. Therefore, the conversion from edb::value80 to a long double in MSVC is not a trivial memcopy. Instead we leverage the FPU directly to load the 80 bits from edb::value80 and store them again in a double, doing the conversion for us.
Note that of course this reduces the precision and for values that can not be represented by a 64bit double it does not work (i.e. exponent too large -> inf, exponent too small -> 0). In order to fully support 80bit doubles, we would need to port a version of sprintf that can deal with these long doubles.
=> Deal with long double in MSVC

plugins/DebuggerCore/unix/linux/PlatformThread.h, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformState.cpp, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformState.h, plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformThread.cpp, plugins/ODbgRegisterView/RegisterView.cpp, plugins/ODbgRegisterView/RegisterView.h, plugins/ODbgRegisterView/armGroups.cpp, plugins/ODbgRegisterView/armGroups.h, src/arch/arm-generic/ArchProcessor.cpp, src/arch/arm-generic/RegisterViewModel.cpp, src/arch/arm-generic/RegisterViewModel.h
VFPvN data registers are still not supported in the Register View. For them there'll need to be some additional work to
1. Check CPU support for formats (`Sn`, `Dn`, `Qn`)
2. Design the layout for this large register file (it doesn't seem a good idea to e.g. show 64 `Sn` registers available on VFPv3 as 64 rows, and even the 32 `Dn` registers as 32 rows).
So this PR only implements display of FPSCR.
=> Add FPSCR to Register View

appveyor.yml
The AppVeyor infrastructure only keeps the most recent micro version of a specific Qt minor version. Thus, hardcoding a specific micro version will eventually fail on AppVeyor. Therefore, we should only use a specific minor version, which will be kept for a long time on the AppVeyor infrastructure.
=> Fix: Appveyor should use most recent micro version of Qt

src/arch/x86-generic/ArchProcessor.cpp, src/capstone-edb/Instruction.cpp, src/capstone-edb/include/Inspection.h
One bug is fixed, and additionally, SIMD scalar integer operands are now formatted according to their signedness as decimal numbers.
=> Fix+improvements in formatting SIMD values in Analysis

plugins/BinaryInfo/symbols.cpp
Fixes #640.
[This random blog](http://em386.blogspot.com/2006/10/elf-no-section-header-no-problem.html) states that the section header is missing if "The removal of the section header is done by changing the elf header e_shnum and e_shentsize values to 0 and then stripping or zeroing out the section header itself.".
=> Do not try to parse a nonexistent Section table

include/Util.h, plugins/ODbgRegisterView/DialogEditFPU.cpp, src/FloatX.cpp
This will allow to enter exact binary representation of floating-point numbers without the need to shift/mask/bias mantissa and exponent into the particular storage format.
=> Add support for entering floating-point numbers in hexfloat format in register edit dialogs

src/capstone-edb/Instruction.cpp
is_SIMD_SI and is_SIMD_USI had no default labels in their switch statements.
=> Add missing default case in is_SIMD_SI/is_SIMD_USI

plugins/ODbgRegisterView/RegisterView.cpp, plugins/ODbgRegisterView/RegisterView.h
At the moment register view font is not updated when settings are changed. This commit fixes that.
Although the change works, could you please review it, because I'm not sure the author intended it to be updated this way.
=> Properly update font in register view when settings are changed

src/Debugger.cpp
One of my latest commits which changed the use of `std::istringstream` to parse floating-point numbers to `std::sto...` resulted in breakage of EDB in non-English locales. Namely, if `LC_NUMERIC` is set to something like `ru_RU.UTF-8`, decimal separator is comma. And since `std::stod` and family, unlike `std::istream`, is locale-aware (too aware, unfortunately), the numbers which passed our `FloatXValidator`, appear rejected in `fullStringToFloat`.
To fix this, EDB must set its `LC_NUMERIC` to `"C"`, which is done by this patch.
=> Set consistent LC_NUMERIC

src/CMakeLists.txt, src/DebugEventHandlers.cpp, src/DebugEventHandlers.h, src/Debugger.cpp, src/edb.cpp
OK. Here is my proposed fix for #650.
This problem is solved by introducing an class called
DebugEventHandlers. It holds IDebugEventHandler* and allows removing
when execute_debug_event_handlers is being in progress.
Here is the copy of its description:
DebugEventHandlers is a container of IDebugEventHandler*. It
supports three operations:
1. add -- Adding IDebugEventHandler*
2. remove -- Removing IDebugEventHandler*
3. execute -- Iterating over added handlers and calling them
The reason why a simple standard container is not enough is
that handlers can be added/removed while the list is being
iterated on. Naive implement would cause accessing an invalid
iterator in this case.
In order to support handler removal during iteration this class
keeps an extra bool (inside_execute_) -- whether …
=> RFC: introduce DebugEventHandlers (fix #650)

edb.desktop
Hello fellow contributors of edb. I made a small change in the `edb.desktop` file, if you like it consinder to accept it :)
As of now, the gentoo ebuild of edb-debugger uses `sed` to alter the description inside the `edb.desktop`, so I thought I could share my idea with a PR. This will help both me to clean up future ebuilds and perhaps other users of the software that want a more descriptive `.desktop` file.
Thanks!
=> Make the desktop's entries somewhat better

CMakeLists.txt
Otherwise on my system, `man edb` doesn't find the man page. And in any case, there's no other `*.1` file in `/usr/share/man`, unlike `/usr/share/man/man1`.
=> Fix installation path of the man page

CMakeLists.txt
If the compiler is g++, any version less than 5 fails to compile EDB. So it's a good idea to check this at CMake stage.
=> Check that g++ version is new enough

src/Debugger.h
=> Fix "No such method Debugger::getCurrentRegisterContextMenuItems()"

plugins/ODbgRegisterView/DialogEditSIMDRegister.cpp
At program startup (before anything is run), valgrind reports uninitialized variable
with the following callstack (reduced for clarity):
Conditional jump or move depends on uninitialised value(s)
...
QString::arg(long long, int, int, QChar) const
QString::arg(int, int, int, QChar) const
ODbgRegisterView::DialogEditSIMDRegister::formatInteger<unsigned char>
ODbgRegisterView::DialogEditSIMDRegister::updateIntegralEntries<unsigned char>
ODbgRegisterView::DialogEditSIMDRegister::updateAllEntriesExcept
ODbgRegisterView::DialogEditSIMDRegister::onHexToggled
QtPrivate::FunctorCall<...>::call
QtPrivate::FunctionPointer<...>::call
QtPrivate::QSlotObject<...>::impl
QMetaObject::activate(QObject *, int, int, void * *)
QAbstractButton::toggled(bool)
...
QAbstractButton::setChecked(bool) …
=> uninitialized array in DialogEditSIMDRegister

plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformState.cpp
It's expected to handle such inputs, and in x86 code it does handle them well, so should in ARM too.
Closes #713
=> Fix crash when PlatformState::gp_register() on ARM is passed an invaid GPR index

src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
Added feature for drawing jump lines on the left side of disassembly view. Kinda missing this one when I was using EDB. (in Windows my goto debugger is x64dbg, so was inspired by that)
Any comment is really appreciated :) (as I have not majorly tested this one yet - only on x86-64 Linux).
=> Draw jump lines on left-side of disassembly view

src/capstone-edb/Instruction.cpp
These two are special cases where, despite a register being an operand, memory access size is still required to be shown explicitly. E.g. `movzx eax, byte [eax]` vs `movzx eax, word [eax]`.
=> Don't remove operand size from movzx/movsx disassembly

include/Configuration.h, src/Configuration.cpp, src/DialogOptions.cpp, src/DialogOptions.ui, src/widgets/QDisassemblyView.cpp, src/widgets/QDisassemblyView.h
Changes made:
1. Added option to disable jump draw
2. Fixed possible crashing when accessing show_addresses_ function 
3. Dock registers badge at the left side of line1
Any comments is really appreciated. :)
=> Add option to disable jump draw

src/Debugger.cpp
As they were reported by leak sanitizer:
Indirect leak of 144 byte(s) in 3 object(s) allocated from:
#0 0x7fcf36539d80 in operator new(unsigned long) (/nix/store/784rh7jrfhagbkydjfrv68h9x3g4gqmk-gcc-8.3.0-lib/lib/libasan.so.5+0xedd80)
#1 0x69f35a in Debugger::on_cpuView_customContextMenuRequested(QPoint const&) /home/ivan/d/edb-debugger/src/Debugger.cpp:1688
Indirect leak of 144 byte(s) in 3 object(s) allocated from:
#0 0x7fcf36539d80 in operator new(unsigned long) (/nix/store/784rh7jrfhagbkydjfrv68h9x3g4gqmk-gcc-8.3.0-lib/lib/libasan.so.5+0xedd80)
#1 0x69f666 in Debugger::on_cpuView_customContextMenuRequested(QPoint const&) /home/ivan/d/edb-debugger/src/Debugger.cpp:1691
=> fix leaking menus in Debugger::on_cpuView_customContextMenuRequested

plugins/ODbgRegisterView/RegisterView.cpp, plugins/ODbgRegisterView/RegisterView.h
After commit 562eb3c2bd3853ac53e031963dd38a744367f821 a message
```
QLayout: Attempting to add QLayout "" to ODbgRegisterView::ODBRegView "ODBRegView", which already has a layout
```
was printed everytime ODBRegView::modelReset is called.
This commit tries to fix this.
=> fix warning message printed in ODBRegView::modelReset

plugins/DebuggerCore/unix/Unix.cpp
Before this PR running
```
edb --run /home/ivan/Документы/a.out
```
(Документы means "Documents" in Russian) would cause heap-buffer-overflow in edb:
```
=================================================================
==26208==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030004bd19b at pc 0x7f933a072274 bp 0x7ffd5dc26860 sp 0x7ffd5dc26010
WRITE of size 36 at 0x6030004bd19b thread T0
#0 0x7f933a072273
#1 0x7f93242f2796 in strcpy bits/string_fortified.h:90
#2 0x7f93242f2796 in DebuggerCorePlugin::Unix::execute_process(QString const&, QString const&, QList<QByteArray> const&) plugins/DebuggerCore/unix/Unix.cpp:179
#3 0x7f93241d6dc5 in DebuggerCorePlugin::DebuggerCore::open(QString const&, QString const&, QList<QByteArray> const&, QString const&) …
```
=> fix heap-buffer-overflow on binary paths containing non-ascii characters

src/SymbolManager.cpp
When program with whitespace in its path is run, edb prints the warning:
```
WARNING: File "/home/ivan/.cache/codef00.com/edb/symbols//home/ivan/My Documents/hello.map" seems corrupt
```
and the list of symbols is empty.
The bug is caused by the fact that the file path is read with istream::operator>> that stops reading at first whitespace. This commit uses std::getline to read the line fully.
=> fix a bug that symbols aren't loaded when executable path contains whitespace

src/Configuration.cpp
In Linux distributions like NixOS and Guix installation path contains hash of all dependencies.
If plugin path is stored in user configuration, edb will break on update due to invalid plugin path.
It can be prevented by saving only non-default plugin path.
Issue is described here: https://github.com/NixOS/nixpkgs/pull/58962#issuecomment-481521588
=> Don't save default plugin path

plugins/DebuggerCore/unix/linux/arch/x86-generic/PlatformThread.cpp
On gcc-11 edb-debugger build fails as:
```
.../x86-generic/PlatformThread.cpp:332:79: error: 'n' is not a constant expression
332 |         return ptrace(PTRACE_POKEUSER, tid_, offsetof(struct user, u_debugreg[n]), value);
|                                                                               ^
```
It's a regression of gcc-11 compared to gcc-10, but it's not
clear if non-constant expressions are guaranteed to work in
general: https://gcc.gnu.org/PR95942. gcc used to accept
simple expressions, but nothing complex.
The change workarounds build failure by avoiding non-constant expression.
=> x86-generic/PlatformThread.cpp: avoid non-constant offsetof for gcc-11

CMakeLists.txt, include/version.h.in, plugins/CheckVersion/CheckVersion.cpp, plugins/DebuggerCore/unix/linux/FeatureDetect.cpp, src/DialogAbout.cpp, src/edb.cpp, src/main.cpp
Using cmake as the central method of managing edb's version. We then use cmake to generate an appropriate version.h that can be used project-wide.
=> CMake version managments of whole project

pkg/fedora/edb.spec
This is a specfile for packaging edb into an RPM for Fedora. Other distros (eg. OpenSUSE) are untested; it certainly won't build on OpenSUSE due to missing dependencies.
I've used this to package edb on COPR (the Fedora user repository) for personal use, but figured I might as well put it here too in case it interests you. With this it should be relatively simple to eg. set up a COPR that automatically builds every GitHub release as soon as you push them, using COPR's webhook functionality.
Building the RPM locally using this is relatively simple:
1. Run `rpmdev-setuptree` to set up the rpmbuild directory in your ~/.
2. Move edb.spec to `~/rpmbuild/SPECS/`
3. Build the RPM with `cd ~/rpmbuild && rpmbuild -ba SPECS/edb.spec`
=> Add Fedora RPM specfile

plugins/BinarySearcher/DialogBinaryString.cpp
Instead of trying to read an entire debuggee process region at
once, read up to 4096 pages at a time. This should reduce memory
issues when running against processes that allocate huge amounts of
memory such as modern games.
In addition, slightly optimize the performance if byte alignment is on.
=> make binary string search read proc mem in chunks

src/CMakeLists.txt
- In the new version of CMP0115 policy extension must also be provided, there is no version.h in PROJECT_SOURCE_DIRECTORY.
- Accept the DEFAULT_PLUGIN_DIR during CMAKE configure and use default value to ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/edb, if not provided.
=> Fix CMP0115 warning and use default DEFAULT_PLUGIN_DIR or accept

include/edb.h, plugins/Bookmarks/BookmarkWidget.cpp, plugins/Bookmarks/BookmarkWidget.h, plugins/Bookmarks/BookmarksModel.cpp, plugins/Bookmarks/BookmarksModel.h, src/edb.cpp
New features:
* Bookmarks now show their symbol name alongside their address, if it can be found.
* Bookmarks have the same icons beside them that addresses do in the disassembly view (breakpoint, current instruction, or both).
* While bookmark view is in focus, "B" will toggle a breakpoint at that address, and "Shift+B" will add a conditional breakpoint.
It's not all done in the optimal way, but I didn't want to change too many things outside of the Bookmark plugin (the only other change I made is a function in the `edb::v1` namespace that returns the current instruction pointer address).
=> Show which bookmarks have breakpoints

src/res/translations/edb_zh_CN.ts
This makes plugins translatable. The full command is:
```
lupdate src plugins -ts ./src/res/translations/edb_zh_CN.ts
```
=> Run lupdate on plugins too
