- include/ArchProcessor.h
- src/arch/x86/ArchProcessor.cpp
- src/arch/x86_64/ArchProcessor.cpp
Sorry for that off by one error. I thought that approach would be more robust. This version must appear much better. Not sure how to deal with register view updater code though.
> Remove a potential source of off-by-one or more serious errors.

- include/Register.h
- src/arch/x86/ArchProcessor.cpp
- src/arch/x86_64/ArchProcessor.cpp
> Fix calculation of effective addresses with smaller then full-width registers

- plugins/DebuggerCore/unix/linux/PlatformState.cpp
This add missing [ER]IP setting code to set_register().
> Fix for issue #203

- include/IState.h
- include/Register.h
- include/State.h
- include/Types.h
- plugins/Analyzer/Analyzer.cpp
- plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
- plugins/DebuggerCore/unix/linux/DebuggerCore.h
- plugins/DebuggerCore/unix/linux/PlatformState.cpp
- plugins/DebuggerCore/unix/linux/PlatformState.h
- plugins/DumpState/DumpState.cpp
- src/Register.cpp
- src/State.cpp
- src/arch/x86-generic/ArchProcessor.cpp
- src/widgets/QDisassemblyView.cpp
This set of commits is a start of gradual changes for EDB to support dynamic debuggee bitness. These commits don't do any drastic changes to behavior, just make the internals easier to later switch to dynamic bitness support. They also do several minor fixes.
I'm planning to do several such merge requests, so that any upstream changes in between wouldn't force me to spend lots of time resolving conflicts.
> Gradual preparation for dynamic debuggee bitness support

- plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
Actually my original code also exhibited undefined behavior. It is legal to read an object of type `T` via a `char*`, but the converse is not. This version should finally settle this.
The fact that your version created a temporary and thus hid the warning is misleading. You may have thought that now the code is OK, but actually it's just not that obvious to the compiler now, but still has UB.
> Fix the UB of accessing char array via T*

- src/arch/x86-generic/ArchProcessor.cpp
This is a fix for current most obvious problems. In the future, the whole syscall analyzer should be reworked, since several mechanisms are valid at once, all with different calling conventions: `sysenter`+`int 0x80` on IA32, `syscall`+`int 0x80` on AMD64 in long mode (and maybe also `sysenter` in long mode or `syscall` in compatibility mode, but I haven't tested these).
> Fix display of function/syscall parameters

- qmake/c++11.pri
> Use -std=c++11 instead of -std=c++0x

- include/IState.h
- include/Register.h
- include/State.h
- plugins/DebuggerCore/unix/linux/PlatformState.cpp
- src/State.cpp
- src/arch/x86-generic/ArchProcessor.cpp
- src/arch/x86-generic/DialogEditFPU.cpp
- src/arch/x86-generic/DialogEditFPU.h
- src/arch/x86-generic/Float80Edit.cpp
- src/arch/x86-generic/Float80Edit.h
- src/src.pro
This set of commits allows to edit FPU Rx registers. Status and control word registers still remain uneditable.
> Make it possible to edit FPU registers

- plugins/DebuggerCore/unix/linux/PlatformEvent.cpp
- src/arch/x86-generic/ArchProcessor.cpp
This makes it easier to understand what happens on FPU/SSE/AVX exceptions and just brings SSE/AVX registers presentation to the level of that of FPU registers.
> Elaborate on floating point exceptions and MXCSR bits

- src/arch/x86-generic/DialogEditSIMDRegister.cpp
- src/arch/x86-generic/DialogEditSIMDRegister.h
Here're some minor fixes in addition to previous merge request.
> Some follow-up fixes

- plugins/SymbolViewer/DialogSymbolViewer.cpp
- src/edb.cpp
> Symbol viewer fix

- plugins/DebuggerCore/unix/linux/PlatformState.cpp
- plugins/DebuggerCore/unix/linux/PlatformState.h
- plugins/DebuggerCore/unix/linux/PlatformThread.cpp
- src/arch/x86-generic/DialogEditGPR.cpp
This allows to finally modify SSE & AVX registers.
> Implement setting SIMD state

- .gitignore
This removes useless clutter in output of e.g. `git status`.
> Add some generated files to gitignore

- plugins/DebuggerCore/unix/linux/PlatformState.cpp
- plugins/DebuggerCore/unix/linux/PlatformState.h
- plugins/DebuggerCore/unix/linux/PlatformThread.cpp
> X86XState fix

- include/Configuration.h
- src/Configuration.cpp
- src/DialogOptions.cpp
- src/DialogOptions.ui
- src/widgets/QDisassemblyView.cpp
This allows the user to disable syntax highlighting in disassembly.
> Syntax highlighting option

- include/IDebugger.h
- plugins/DebuggerCore/DebuggerCoreBase.cpp
- plugins/DebuggerCore/DebuggerCoreBase.h
- plugins/DebuggerCore/unix/DebuggerCoreUNIX.cpp
- plugins/DebuggerCore/unix/DebuggerCoreUNIX.h
- plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
- plugins/DebuggerCore/unix/linux/DebuggerCore.h
- src/Debugger.cpp
> Exec error reporting

- src/arch/x86-generic/ArchProcessor.cpp
> Fix lack of GPR comment for rAX

- plugins/DebuggerCore/unix/linux/PlatformProcess.cpp
> Fix reading negative addresses like 0xffffffffff600000

- src/arch/x86-generic/ArchProcessor.cpp
Otherwise not only this unuseful information is shown, but sometimes it even
becomes misleading: e.g. 64-bit EDB launches a 32-bit process, that process has
orig_eax==59, which is then decoded by EDB as return from oldolduname(), not
even execve(). Same for 32-bit EDB launching a 64-bit process, where
orig_rax==11 would look like return from munmap().
> Prevent reporting false returns from execve syscall

- include/Register.h
- src/edb.cpp
See commit messages for details.
> Make Register::valid() interface easier to use and avoiding some mistakes

- src/arch/x86-generic/ArchProcessor.cpp
Otherwise analysis view sometimes has quite strange, seemingly random order of entries. Now it'll at least be lexicographically sorted.
> Sort analysis strings

- src/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eteran/edb-debugger/463)
> fixed building with Qt5

- plugins/BinarySearcher/DialogBinaryString.cpp
This made finding a binary constant in my debuggee take about 5-10 seconds instead of not being complete after several minutes.
The main issue was the pointless usage of `ByteShiftArray` when we already had a contiguous view of the region memory. Constantly popping bytes into and out of the BSA destroyed all performance in my profiler (80% of the runtime). Calls to `region->size()` were second on the list (13% of runtime) because we called it inside the while loop.
> Improve Binary String search performance

- src/widgets/QDisassemblyView.cpp
- src/widgets/QDisassemblyView.h
Reverts eteran/edb-debugger#513
> Revert "Cache Syntax Highlighting results"

- src/widgets/QDisassemblyView.cpp
Fixes #520. At least, the most obvious parts of it.
> Fix render not respecting region size

- src/widgets/QDisassemblyView.cpp
- src/widgets/QDisassemblyView.h
Related to #414. Try this change @eteran it works for me. Not sure why yours did not, though.
> Fix font cache

- src/widgets/QDisassemblyView.cpp
- src/widgets/QDisassemblyView.h
> Don't count last partial line as in viewport

- src/widgets/QDisassemblyView.cpp
- src/widgets/QDisassemblyView.h
This allows to navigate code using keyboard more easily.
> Place selection at the same line number after PageUp/PageDown as was before it

- src/edb.cpp
> make read_instruction_bytes update *size correctly

- include/Util.h
- plugins/Assembler/OptionsPage.cpp
- plugins/Assembler/xml/assemblers.xml
- plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
- plugins/InstructionInspector/Plugin.cpp
- src/Configuration.cpp
- src/Debugger.cpp
- src/arch/arm-generic/ArchProcessor.cpp
- src/capstone-edb/Inspection.cpp
- src/capstone-edb/Instruction.cpp
- src/capstone-edb/include/Inspection.h
- src/capstone-edb/include/Instruction.h
- src/widgets/QDisassemblyView.cpp
- src/widgets/SyntaxHighlighter.cpp
Also added ability to step over and fixed _Follow_ functionality. Single-stepping is still unsupported, but step over+Follow+RunTo is better than nothing :)
Also made ARM Assembler plugin work, currently only for ARM mode (i.e. not Thumb).
> Some work on ARM disassembly syntax highlighting + Thumb support

- plugins/DebuggerCore/unix/linux/DebuggerCore.cpp
- plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformThread.cpp
- src/Debugger.cpp
- src/capstone-edb/include/Instruction.h
- src/widgets/SyntaxHighlighter.cpp
Major changes:
* Non-`SIGTRAP` breakpoints finally behave as first-class citizens
* ARM `pop` instruction can be single-stepped
* _Run until return_ functionality (on x86) behaves in a sane way WRT events other than breakpoints and is more robust and understandable by the user in general
> Assorted fixes and improvements

- include/ArchProcessor.h
- include/Status.h
- plugins/DebuggerCore/unix/linux/arch/arm-generic/PlatformThread.cpp
- src/arch/arm-generic/ArchProcessor.cpp
- src/arch/x86-generic/ArchProcessor.cpp
- src/capstone-edb/Inspection.cpp
- src/edb.cpp
This lets EDB single-step `LDR` instruction when it modifies `PC`. Also some minor issues are fixed.
> Implement single-stepping LDR PC, [...]

- src/edb.cpp
> Fix "Pop DWORD" popping the wrong number of bytes

- src/DialogAttach.cpp
> Make DialogAttach usable again

- include/Types.h
- src/CMakeLists.txt
- src/Debugger.cpp
- src/session/SessionError.cpp
- src/session/SessionError.h
- src/session/SessionManager.cpp
- src/session/SessionManager.h
- src/widgets/QDisassemblyView.cpp
- src/widgets/QDisassemblyView.h
I started to work on #527 and made a first (very basic) version that saves the comments in the session file and restores them when attaching the binary again. Before going any further with it i would like to hear from you if the code is even remotely good (my first ever contribution to any project)
> SessionManager implemented with comment saving function #527

- include/Util.h
This works around gcc bug 86409.
> Fix reading of denormal numbers

- include/Util.h
Now this supports denormals, hexfloats and denormal hexfloats without ugly work-arounds via `std::istringstream`.
See also [my post at StackOverflow](https://stackoverflow.com/a/51204289/673852) for details on `std::stod` et al. and their relation to `std::out_of_range` and `ERANGE`.
> Simplify parsing of floating-point values

- src/session/SessionManager.cpp
This is follow up of last comments in #628.
Now we show error messages when session file fails to open (for example in case permission are denied).
> show error message when session file fails to open

- src/widgets/QDisassemblyView.cpp
- src/widgets/QDisassemblyView.h
Previously, some jump arrows might be overlapped or being so close together (which makes it not to look nice).
This PR attempted to fix that, and now all jump arrows fit nicely.  :)
> Improve jump arrows drawing

- src/widgets/QDisassemblyView.cpp
This is a pixel-hunting change, making the arrows nicer.
> Align jump arrow lines to pixel grid and avoid their overlapping with arrow tips

- plugins/ODbgRegisterView/RegisterView.cpp
- plugins/ODbgRegisterView/RegisterView.h
> Make it possible to easily restore a hidden register group

- plugins/Analyzer/Analyzer.cpp
- plugins/ProcessProperties/DialogProcessProperties.cpp
- src/Font.cpp
- src/graph/GraphWidget.cpp
- src/widgets/QDisassemblyView.cpp
Squashing most warnings related to deprecation. I think that are left are in qhexview
which is its own project
> Squashing most warnings related to deprecation.

- plugins/Bookmarks/Bookmarks.cpp
- plugins/DebuggerErrorConsole/Plugin.cpp
- plugins/DebuggerErrorConsole/Plugin.h
- plugins/ODbgRegisterView/Plugin.cpp
- src/Debugger.cpp
- src/Debugger.h
- src/Debugger.ui
- src/edb.cpp
- src/main.cpp
- src/res/icons/breeze-dark-edb/16x16/dialog-information.svg
- src/res/icons/breeze-dark-edb/24x24/dialog-information.svg
- src/res/icons/breeze-dark-edb/64x64/dialog-information.svg
- src/res/icons/breeze-edb/16x16/dialog-information.svg
- src/res/icons/breeze-edb/24x24/dialog-information.svg
- src/res/icons/breeze-edb/64x64/dialog-information.svg
working on handling the UI in a more custom way. The idea being that we'll have more control over how the UI operates than we'd get with using the designer alone
We'll still use the designer for the really basic stuff (toolbar, menu, status bar), but the CPU/Data/Stack/etc views have long been too complex to represent in
the designer meaningfully (unless we made designer plugins... but that hardly seems worth it).
> A more manually coded UI, to allow more complex future customizations

- .clang-format
- .github/workflows/build.yaml
> trying to add a git workflow

- pkg/fedora/edb.spec
- plugins/BreakpointManager/BreakpointManager.cpp
- plugins/BreakpointManager/BreakpointManager.h
- plugins/BreakpointManager/CMakeLists.txt
- src/CMakeLists.txt
- src/Debugger.cpp
- src/Debugger.h
- src/Debugger.ui
- src/DialogBreakpoints.cpp
- src/DialogBreakpoints.h
- src/DialogBreakpoints.ui
integrate breakpoint manager into core code
> integrate breakpoint manager into core code

- src/Debugger.cpp
Parameters for xfce4-terminal are a bit different
> Support for XFCE terminal

- src/res/translations/edb_zh_CN.ts
> Translation Updates
